app = "gpt-researcher-frontend"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile.frontend"

[env]
  PORT = "3000"
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://gpt-researcher-backend.fly.dev:8000"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1