app = "gpt-researcher-backend"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile.backend"

[env]
  PYTHONUNBUFFERED = "1"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 8000
    handlers = ["http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[vm]]
  memory = "16gb"
  cpu_kind = "shared"
  cpus = 8