name: GPTR tests
run-name: ${{ github.actor }} ran the GPTR tests flow
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:
  # pull_request:
  #   types: [opened, synchronize]

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: tests
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
      LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and test backend
        run: |
          docker-compose --profile test run --rm gpt-researcher-tests

      - name: Build and test frontend
        run: |
          cd frontend/nextjs
          npm install --legacy-peer-deps
          npm run build