name: Fly Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy-backend:
    name: Deploy backend
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy backend to fly.io
        run: |
          cp Dockerfile.backend Dockerfile
          flyctl deploy --app gpt-researcher-backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-frontend:
    name: Deploy frontend
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-backend
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy frontend to fly.io
        working-directory: frontend
        run: |
          cp ../Dockerfile.frontend Dockerfile
          flyctl deploy --app gpt-researcher-frontend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}