name: Fly Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        run: |
          # Set environment variables in fly.io
          flyctl secrets set OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"
          flyctl secrets set TAVILY_API_KEY="${{ secrets.TAVILY_API_KEY }}"
          flyctl secrets set LANGCHAIN_API_KEY="${{ secrets.LANGCHAIN_API_KEY }}"
          # Deploy the application
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
          LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}